n=int(input())
mat=list(map(int,input().split()))
exe=['chest','biceps','back']
arr=[0,0,0]
i=0
while(n>0):
    n-=3
    try:
        arr[i%3]+=mat[i]
        arr[(i+1)%3]+=mat[i+1]
        arr[(i+2)%3]+=mat[i+2]
    except:
        break
    i+=3
ind=arr.index(max(arr))
print(exe[ind])